---
title: "Explore Boundaries for classifiers"
format: html
---

## Background

When working with classification problems, it is important to visualize the decision boundaries of a classification model to understand the method being used and to compare it with alternative approaches. 

The motivation for this project is to have an R package that allows users to explore decision boundaries for both existing and new classification methods. An initial approach is to define 2D scatter plots under different simulation scenarios, allowing exploration of various boundary characteristics. For example, we can examine how boundaries change with different levels of group variance, class imbalance, or model complexity, among others.

Additionally, in high-dimensional settings, boundaries can be explored using tour methods for multivariate data visualization available in the tourr package, which allows users to explore the high-dimensional structure of the data and the resulting model fits.


## Related work

The [`PPtreeExt`](https://github.com/natydasilva/PPtreeExt) package (Enhanced Projection Pursuit Tree Classifier) available on CRAN, includes a Shiny app to explore classification boundaries. The tool includes methods for simulating 2D classification problems and displays the decision boundaries generated by different algorithms: CART, PPtree, and the proposed extensions (implemented in `rpart`, `PPtreeViz`, and `PPtreeExt`, respectively). 

The app is available in the `PPtreeExt` package along with the implementation of the modified algorithm (app also available at <https://natyds.shinyapps.io/explorapp/>). It allows users to generate 2D data sets with different types of separations and compare the model fits for the modified and the original algorithm. This was an essential tool in constructing the new algorithm, because as it provides a side-by-side visualization of prediction boundaries to identify data patterns in which the different methods perform best. 

We have a working paper at <https://arxiv.org/abs/2602.21130> describing the `PPtreeExt` package and the application in more detail. In this paper we also include two visual diagnostics to understand the performance of the modified algorithm. The first visual diagnostic is to use the app described before to explore the decision boundaries for different simulation scenarios. The second visual diagnostic is to use tours available in the
tourr package to examine the high-dimensional structure of data sets
and the resulting model fits, where the modified algorithm outperforms other classifiers. This explains the performance comparison results and intuition for why the modified algorithm performs better.

A previous related work is the R package `classifly` which was useful to explore classification models in high dimensions. `classifly` was removed from the CRAN repository (Archived on 2025-09-04 at the maintainer's request). This package description was: Given $p$-dimensional training data containing $d$ groups (the design space), a classification algorithm (classifier) predicts which group new data belongs to. Generally the input to these algorithms is high dimensional, and the boundaries between groups will be high dimensional and perhaps curvilinear or multi-faceted. This package implements methods for understanding the division of space between the groups. 
This package was designed to visualize high-dimensional classification boundaries using `GGobi` software. 

GSoC would be to extend this app into a separate R package to create a more general tool for exploring classification boundaries defined by a
broader set of methods, including additional simulation scenarios and possibly more complex problems. An initial step has been taken to include the app in a separated R package `classbound` available at <https://github.com/natydasilva/classbound>.



## Details of your coding project

The final goal is to extend `classbound` functionality in several ways and make it more suitable for general use. There are three major extensions to work on: 

1. **More classifiers**: Currently the package works on three classification methods, so it is important to add more available classifiers, eventually allowing user-defined classification method.  
2. **Data simulation**: Include more flexible ways to simulate the data and some real data sets examples to choose from. 
3. **High dimensions**: Extend funcionallity to high dimension settings using tour methods for multivariate data visualization available in the `tourr` R package. 


Important aspects of R package development needs to be considered too; these includes

- Document the code and provide examples of usage of the new functionality
- Write a vignette providing guidance on using the package 
- Include a webpage for the package


## Expected impact

This package provides a useful tool for exploring the boundaries defined by any classification method, following the philosophy of seeing the data in the model space to understand what a classifier is really doing — whether it is appropriate for the problem being analyzed — and for comparing it with other classification methods.



## Mentors

Contributors, please contact mentors below after completing at least one
of the tests below.

- EVALUATING MENTOR: Natalia da Silva <natalia.dasilva@fcea.edu.uy> is the
  author of R packages `PPforest`, `PPtreeExt` among others and was contributor of GSOC in 2017 edition.
- Co-mentor: Ignacio Alvarez-Castro <ignacio.alvarez@fcea.edu.uy> is an expert in statistics and has collaborated in `preDose`, `SpICE` and `jitter2D` which are not available on CRAN and are under development.

## Tests

Contributors, please do one or more of the following tests before
contacting the mentors above.


- Easy: Include a new classification method for comparison in the app's tabset panels. Select an existing tree-based method available on CRAN. At the end you should have in each tabset panel the four methods to compare.

- Medium: Using a grand tour, compare the boundaries from the `rpart` and `PPtreeExt` model on the  data69-1 dataset available in `classbound` package (https://github.com/natydasilva/classbound). Refer to Figure 12, subplots b and c in <https://arxiv.org/abs/2602.21130>. Use as a book reference **Interactively exploring high-dimensional data and models in R**  <https://dicook.github.io/mulgar_book/15-forests.html> in particular Chapter 15.

- Hard: Include a new tabset panel in the explorapp to simulate the data by allowing users to draw it with the mouse. This will allow users to explore the boundaries for data sets with different shapes and characteristics, which are not easily simulated using existing methods. You can check similar ideas in the `drawdata` Python library which contains Jupyter widgets that allow you to draw a dataset in a Jupyter notebook. (<https://github.com/koaning/drawdata>) or explore `sillysplines` R package which  gives you a simple HTMLWidget that can draw silly little linear splines in an HTML widget and then download the coordinates to create custom datasets (<https://janithwanni.github.io/sillysplines/>).

## Solutions of tests

Contributors, please post a link to your test results here.

- EXAMPLE CONTRIBUTOR 1 NAME, LINK TO GITHUB PROFILE, LINK TO TEST
  RESULTS.
